# Important Notes:
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Project
version=25.3.0.1
group=net.reentityoutliner
java_version=21

# Common
minecraft_version=1.21.9
mod_name=ReEntityOutliner
mod_author=SioGabx
mod_id=reentityoutliner
license=MIT
credits=adamviola
description=Allows you to select entity types to outline, making them visible through all obstructions within render distance.
minecraft_version_range=[1.21.9, 1.22)
homepage=https://legacy.curseforge.com/minecraft/mc-mods/re-entity-outliner
sources=https://github.com/SioGabx/ReEntityOutliner
issues_page=https://github.com/SioGabx/ReEntityOutliner/issues
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.9-20250930.151910

# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.21
parchment_version=2024.11.10

# Fabric
# check these on https://fabricmc.net/develop/
#note : change loader_version to fabric_loader_version
fabric_loader_version=0.17.2
# Fabric API
fabric_version=0.134.0+1.21.9

# NeoForge
#https://neoforged.net/
neoforge_version=21.9.15-beta
neoforge_loader_version_range=[4,)

# Forge
#https://files.minecraftforge.net/net/minecraftforge/forge/
forge_version=59.0.3
forge_loader_version_range=[59,)

#loom_version -> change in build.gradle

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false


# Dependencies
# ModMenu https://modrinth.com/mod/mOgUt4GM/versions
modmenu_version=16.0.0-rc.1
modmenu_versions=>16
