# Fabric Loom https://mvnrepository.com/artifact/net.fabricmc/fabric-loom
#dont forget to update in build.gradle
#loom_version=1.9.2

# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop/
minecraft_version=1.21.5
yarn_mappings=1.21.5+build.1
loader_version=0.16.13

# Fabric API
fabric_version=0.121.0+1.21.5

# Mod Properties
mod_version=1.5.4
maven_group = net.reentityoutliner
archives_base_name = re-entity-outliner



# Dependencies
# ModMenu https://modrinth.com/mod/mOgUt4GM/versions
modmenu_version=13.0.0
modmenu_versions=>10
