# Important Notes:
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.
# https://github.com/maxuser0/minescript


# Project
version=26.1.2.3
group=net.reentityoutliner
java_version=25

# Common
minecraft_version=26.1.1
mod_name=ReEntityOutliner
mod_author=SioGabx
mod_id=reentityoutliner
license=MIT
credits=adamviola
description=Allows you to select entity types to outline, making them visible through all obstructions within render distance.
minecraft_version_range=[26, 26.2)
homepage=https://legacy.curseforge.com/minecraft/mc-mods/re-entity-outliner
sources=https://github.com/SioGabx/ReEntityOutliner
issues_page=https://github.com/SioGabx/ReEntityOutliner/issues


# Fabric
# check these on https://fabricmc.net/develop/
#note : change loader_version to fabric_loader_version
fabric_loader_version=0.18.4
# Fabric API
fabric_version=0.145.4+26.1.2

# NeoForge
#https://neoforged.net/
neoforge_version=26.1.2.7-beta
neoforge_loader_version_range=[4,)
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.1.2-1

# Forge, see https://files.minecraftforge.net/net/minecraftforge/forge/ for new versions
forge_version=60.0.0
forge_loader_version_range=[60,)

#loom_version -> change in build.gradle

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false


# Dependencies
# ModMenu https://modrinth.com/mod/mOgUt4GM/versions
modmenu_version=18.0.0-alpha.8
modmenu_versions=>17
